version: '3.4'

services:
  flypackbot:
    image: ${DOCKER_REGISTRY-}flypackbot
    build:
      context: .
      dockerfile: FlypackBot/Dockerfile
    environment:
      - TZ=${TIMEZONE}
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - Flypack__Username=${FLYPACK_USERNAME}
      - Flypack__Password=${FLYPACK_PASSWORD}
      - Telegram__AccessToken=${TELEGRAM_ACCESS_TOKEN}
      - Telegram__AuthorizedUsers__0=${TELEGRAM_AUTHORIZED_USERS_0}
      - Telegram__ChannelIdentifier=${TELEGRAM_CHANNEL_IDENTIFIER}
      - Telegram__MaxMessageLength=${TELEGRAM_MAXIMUM_MESSAGE_LENGTH}
