version: '3.4'

services:
  flypack.bot:
    image: ${DOCKER_REGISTRY-}flypackbot
    container_name: flypack.bot
    build:
      context: .
      dockerfile: FlypackBot/Dockerfile
    environment:
      - TZ=${TIMEZONE}
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - Flypack__PrivateKey=${FLYPACK_PRIVATE_KEY}
      - Flypack__FetchInterval=${FLYPACK_FETCH_INTERVAL}
      - Telegram__AccessToken=${TELEGRAM_ACCESS_TOKEN}
      - Telegram__AuthorizedUsers__0=${TELEGRAM_AUTHORIZED_USERS_0}
      - Telegram__ChannelIdentifier=${TELEGRAM_CHANNEL_IDENTIFIER}
      - Telegram__MaxMessageLength=${TELEGRAM_MAXIMUM_MESSAGE_LENGTH}
      - Telegram__MaxMessageEntities=${TELEGRAM_MAXIMUM_MESSAGE_ENTITIES}
      - Telegram__ConsecutiveMessageInterval=${TELEGRAM_CONSECUTIVE_MESSAGES_INTERVAL}
      - MongoDb__DatabaseName=${MONGO_INITDB_DATABASE}
      - MongoDb__ConnectionString=${MONGO_CONNECTION_STRING}

  flypack.db:
    image: mongo:latest
    container_name: flypack.db
    environment:
      TZ: ${TIMEZONE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_USERNAME: ${MONGO_INITDB_USERNAME}
      MONGO_INITDB_PASSWORD: ${MONGO_INITDB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - ./.mongodb/entrypoint/:/docker-entrypoint-initdb.d/
      - ./.mongodb/home:/home/mongodb/
      - ./.mongodb/data/db/:/data/db/
      - ./.mongodb/data/log/:/var/log/mongodb/
    ports:
      - "27017:27017"