//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlypackBot.L10n {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings_fr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings_fr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlypackBot.L10n.strings.fr", typeof(strings_fr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre tentative de connexion a été approuvée..
        /// </summary>
        internal static string AllowedLoginAttemptMessage {
            get {
                return ResourceManager.GetString("AllowedLoginAttemptMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hmm... bizarre, apparemment quelqu&apos;un s&apos;est déjà connecté avec ce compte. Donnez-moi un peu de temps pendant que je réfléchis..
        /// </summary>
        internal static string AlreadyLoggedInWithThatAccountMessage {
            get {
                return ResourceManager.GetString("AlreadyLoggedInWithThatAccountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚠️ Je vous conseille de changer votre mot de passe dès que possible..
        /// </summary>
        internal static string ChangeYourPasswordWarningMessage {
            get {
                return ResourceManager.GetString("ChangeYourPasswordWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Désolé... votre tentative de connexion a été refusée..
        /// </summary>
        internal static string DeniedLoginAttemptMessage {
            get {
                return ResourceManager.GetString("DeniedLoginAttemptMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string DescriptionField {
            get {
                return ResourceManager.GetString("DescriptionField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Je vous connais? ಠ_ಠ&quot;.
        /// </summary>
        internal static string DontKnowYouMessage {
            get {
                return ResourceManager.GetString("DontKnowYouMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des packages vides 📭.
        /// </summary>
        internal static string EmptyPackageListMessage {
            get {
                return ResourceManager.GetString("EmptyPackageListMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre nouveau mot de passe ne peut pas être un message vide. 😑.
        /// </summary>
        internal static string EmptyPasswordMessage {
            get {
                return ResourceManager.GetString("EmptyPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}\nListe, réponse: *{1}*.
        /// </summary>
        internal static string InlineQueryAnswerMessage {
            get {
                return ResourceManager.GetString("InlineQueryAnswerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to autoriser.
        /// </summary>
        internal static string LoginAttemptAllowKeyword {
            get {
                return ResourceManager.GetString("LoginAttemptAllowKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autoriser.
        /// </summary>
        internal static string LoginAttemptAllowText {
            get {
                return ResourceManager.GetString("LoginAttemptAllowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nier.
        /// </summary>
        internal static string LoginAttemptDenyKeyword {
            get {
                return ResourceManager.GetString("LoginAttemptDenyKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nier.
        /// </summary>
        internal static string LoginAttemptDenyText {
            get {
                return ResourceManager.GetString("LoginAttemptDenyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hé {0}, l&apos;utilisateur {1} essaie de se connecter avec votre compte Flypack, ça vous convient ?.
        /// </summary>
        internal static string LoginAttemptRequestPermissionMessage {
            get {
                return ResourceManager.GetString("LoginAttemptRequestPermissionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salut {0}! J&apos;ai pu me connecter avec votre utilisateur, maintenant je vais surveiller l&apos;état de vos colis..
        /// </summary>
        internal static string LoginWelcomeMessage {
            get {
                return ResourceManager.GetString("LoginWelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to non.
        /// </summary>
        internal static string NoKeyword {
            get {
                return ResourceManager.GetString("NoKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non.
        /// </summary>
        internal static string NoText {
            get {
                return ResourceManager.GetString("NoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous avez {0} packages en cours de traitement.
        /// </summary>
        internal static string PackagesInProcessMessage {
            get {
                return ResourceManager.GetString("PackagesInProcessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statut des colis.
        /// </summary>
        internal static string PackageStatus {
            get {
                return ResourceManager.GetString("PackageStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lb.
        /// </summary>
        internal static string PoundsText {
            get {
                return ResourceManager.GetString("PoundsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reçu par.
        /// </summary>
        internal static string ReceivedByField {
            get {
                return ResourceManager.GetString("ReceivedByField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez m&apos;envoyer votre nom d&apos;utilisateur et votre mot de passe, afin que je puisse surveiller vos colis et leur statut. Ne vous inquiétez pas, je garderai vos informations d&apos;identification en sécurité.\n\nEnvoyez-les de cette façon : _nom d&apos;utilisateur_, _mot de passe_..
        /// </summary>
        internal static string SendUsernameAndPasswordMessage {
            get {
                return ResourceManager.GetString("SendUsernameAndPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez m&apos;envoyer votre nom d&apos;utilisateur et votre mot de passe.\n\nEnvoyez-les comme ceci : *nom d&apos;utilisateur, mot de passe*, en utilisant une virgule (,) entre les deux..
        /// </summary>
        internal static string SendUsernameAndPasswordSecondMessage {
            get {
                return ResourceManager.GetString("SendUsernameAndPasswordSecondMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statut.
        /// </summary>
        internal static string StatusField {
            get {
                return ResourceManager.GetString("StatusField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voulez-vous vraiment arrêter le bot ?.
        /// </summary>
        internal static string StopBotConfirmationMessage {
            get {
                return ResourceManager.GetString("StopBotConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to À partir de ce moment, vous ne recevrez plus de notifications sur les forfaits associés au compte FLY-{0}. L&apos;utilisateur initialement connecté a arrêté les fonctions du bot.\nVous pouvez vous connecter vous-même à l&apos;aide de la commande /start..
        /// </summary>
        internal static string StoppedBotAuthorizedUsersMessage {
            get {
                return ResourceManager.GetString("StoppedBotAuthorizedUsersMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De plus, les utilisateurs que vous avez précédemment autorisés ont été supprimés et ne recevront plus de notifications..
        /// </summary>
        internal static string StoppedBotFollowUpMessage {
            get {
                return ResourceManager.GetString("StoppedBotFollowUpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to À partir de ce moment, vous ne recevrez plus de notifications concernant vos colis. Dans le même temps, les informations relatives à votre utilisateur ont été supprimées..
        /// </summary>
        internal static string StoppedBotMessage {
            get {
                return ResourceManager.GetString("StoppedBotMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code de suivi.
        /// </summary>
        internal static string TrackingField {
            get {
                return ResourceManager.GetString("TrackingField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le mot de passe a été mis à jour. 🎉.
        /// </summary>
        internal static string UpdatedPasswordMessage {
            get {
                return ResourceManager.GetString("UpdatedPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nom d&apos;utilisateur, mot de passe.
        /// </summary>
        internal static string UsernameAndPasswordPlaceholder {
            get {
                return ResourceManager.GetString("UsernameAndPasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il me semble que nous sommes déjà passés par là, peut-être avez-vous déjà envoyé cette commande auparavant. _Déjà vu_.
        /// </summary>
        internal static string WeHaveAlreadyMetMessage {
            get {
                return ResourceManager.GetString("WeHaveAlreadyMetMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lester.
        /// </summary>
        internal static string WeightField {
            get {
                return ResourceManager.GetString("WeightField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonjour! Comme vous le savez peut-être déjà, ce bot vous aidera dans le suivi de vos colis [Flypack](https://www.flypack.com.do).\n_Ce bot n&apos;a aucun lien juridique avec la société Flypack ou ses associés._.
        /// </summary>
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le nouveau mot de passe est incorrect. 🥴&quot;.
        /// </summary>
        internal static string WrongPasswordMessage {
            get {
                return ResourceManager.GetString("WrongPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Nom d&apos;utilisateur et mot de passe erronés*\nVeuillez m&apos;envoyer votre nom d&apos;utilisateur et votre mot de passe une fois de plus.\n\nEnvoyez-les de cette façon : _nom d&apos;utilisateur_, _mot de passe_..
        /// </summary>
        internal static string WrongUsernameAndPasswordMessage {
            get {
                return ResourceManager.GetString("WrongUsernameAndPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to oui.
        /// </summary>
        internal static string YesKeyword {
            get {
                return ResourceManager.GetString("YesKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oui.
        /// </summary>
        internal static string YesText {
            get {
                return ResourceManager.GetString("YesText", resourceCulture);
            }
        }
    }
}
