//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlypackBot.L10n {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlypackBot.L10n.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your login attempt has been approved..
        /// </summary>
        internal static string AllowedLoginAttemptMessage {
            get {
                return ResourceManager.GetString("AllowedLoginAttemptMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hmm... odd, apparently someone has already logged in with that account. Give me some time while I figure this out..
        /// </summary>
        internal static string AlreadyLoggedInWithThatAccountMessage {
            get {
                return ResourceManager.GetString("AlreadyLoggedInWithThatAccountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚠️ I would advise you to change your password as soon as possible..
        /// </summary>
        internal static string ChangeYourPasswordWarningMessage {
            get {
                return ResourceManager.GetString("ChangeYourPasswordWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry... your login attempt was denied..
        /// </summary>
        internal static string DeniedLoginAttemptMessage {
            get {
                return ResourceManager.GetString("DeniedLoginAttemptMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string DescriptionField {
            get {
                return ResourceManager.GetString("DescriptionField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Do I know you? ಠ_ಠ&quot;.
        /// </summary>
        internal static string DontKnowYouMessage {
            get {
                return ResourceManager.GetString("DontKnowYouMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty packages list 📭.
        /// </summary>
        internal static string EmptyPackageListMessage {
            get {
                return ResourceManager.GetString("EmptyPackageListMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your new password cannot be a blank message. 😑.
        /// </summary>
        internal static string EmptyPasswordMessage {
            get {
                return ResourceManager.GetString("EmptyPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}\nListo, respuesta: *{1}*.
        /// </summary>
        internal static string InlineQueryAnswerMessage {
            get {
                return ResourceManager.GetString("InlineQueryAnswerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to allow.
        /// </summary>
        internal static string LoginAttemptAllowKeyword {
            get {
                return ResourceManager.GetString("LoginAttemptAllowKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow.
        /// </summary>
        internal static string LoginAttemptAllowText {
            get {
                return ResourceManager.GetString("LoginAttemptAllowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deny.
        /// </summary>
        internal static string LoginAttemptDenyKeyword {
            get {
                return ResourceManager.GetString("LoginAttemptDenyKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deny.
        /// </summary>
        internal static string LoginAttemptDenyText {
            get {
                return ResourceManager.GetString("LoginAttemptDenyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey {0}, the user {1} is trying to login with your Flypack account, are you ok with this?.
        /// </summary>
        internal static string LoginAttemptRequestPermissionMessage {
            get {
                return ResourceManager.GetString("LoginAttemptRequestPermissionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi {0}! I was able to log in with your user, now I will monitor the status of your packages..
        /// </summary>
        internal static string LoginWelcomeMessage {
            get {
                return ResourceManager.GetString("LoginWelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.
        /// </summary>
        internal static string NoKeyword {
            get {
                return ResourceManager.GetString("NoKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string NoText {
            get {
                return ResourceManager.GetString("NoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have {0} packages in process.
        /// </summary>
        internal static string PackagesInProcessMessage {
            get {
                return ResourceManager.GetString("PackagesInProcessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packages Status.
        /// </summary>
        internal static string PackageStatus {
            get {
                return ResourceManager.GetString("PackageStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lb.
        /// </summary>
        internal static string PoundsText {
            get {
                return ResourceManager.GetString("PoundsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received by.
        /// </summary>
        internal static string ReceivedByField {
            get {
                return ResourceManager.GetString("ReceivedByField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please send me your username and password, so I can monitor your packages and their status. Don&apos;t worry, I&apos;ll keep your credentials safe.\n\nSend them this way: _username, password_.
        /// </summary>
        internal static string SendUsernameAndPasswordMessage {
            get {
                return ResourceManager.GetString("SendUsernameAndPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please send me your username and password.\n\nSend them like this: *username, password*, using a comma (,) in between..
        /// </summary>
        internal static string SendUsernameAndPasswordSecondMessage {
            get {
                return ResourceManager.GetString("SendUsernameAndPasswordSecondMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string StatusField {
            get {
                return ResourceManager.GetString("StatusField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to stop the bot?.
        /// </summary>
        internal static string StopBotConfirmationMessage {
            get {
                return ResourceManager.GetString("StopBotConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From this moment you will no longer receive notifications about the packages associated with the FLY-{0} account. The original logged in user has stopped the bot&apos;s functions.\nYou can log in yourself using the /start command..
        /// </summary>
        internal static string StoppedBotAuthorizedUsersMessage {
            get {
                return ResourceManager.GetString("StoppedBotAuthorizedUsersMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Also, the users that you have previously authorized have been removed and will no longer receive notifications..
        /// </summary>
        internal static string StoppedBotFollowUpMessage {
            get {
                return ResourceManager.GetString("StoppedBotFollowUpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From this moment you will no longer receive notifications about your packages. At the same time, the information related to your user has been deleted..
        /// </summary>
        internal static string StoppedBotMessage {
            get {
                return ResourceManager.GetString("StoppedBotMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking.
        /// </summary>
        internal static string TrackingField {
            get {
                return ResourceManager.GetString("TrackingField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password has been updated. 🎉.
        /// </summary>
        internal static string UpdatedPasswordMessage {
            get {
                return ResourceManager.GetString("UpdatedPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to username, password.
        /// </summary>
        internal static string UsernameAndPasswordPlaceholder {
            get {
                return ResourceManager.GetString("UsernameAndPasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It seems to me that we have already been through this, perhaps you have already sent that command before. _Déjà vu_.
        /// </summary>
        internal static string WeHaveAlreadyMetMessage {
            get {
                return ResourceManager.GetString("WeHaveAlreadyMetMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        internal static string WeightField {
            get {
                return ResourceManager.GetString("WeightField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello! As you may already know, this bot will help you with the tracking of your [Flypack](https://www.flypack.com.do) packages.\n_This bot does not have any legal relationship with the company Flypack or its associates._.
        /// </summary>
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password is incorrect. 🥴&quot;.
        /// </summary>
        internal static string WrongPasswordMessage {
            get {
                return ResourceManager.GetString("WrongPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Wrong username and password*\nPlease send me your username and password one more time.\n\nSend them this way: _username, password_.
        /// </summary>
        internal static string WrongUsernameAndPasswordMessage {
            get {
                return ResourceManager.GetString("WrongUsernameAndPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yes.
        /// </summary>
        internal static string YesKeyword {
            get {
                return ResourceManager.GetString("YesKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string YesText {
            get {
                return ResourceManager.GetString("YesText", resourceCulture);
            }
        }
    }
}
