//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlypackBot.L10n {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings_es {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings_es() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlypackBot.L10n.strings.es", typeof(strings_es).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu inicio de sesión ha sido aprobado..
        /// </summary>
        internal static string AllowedLoginAttemptMessage {
            get {
                return ResourceManager.GetString("AllowedLoginAttemptMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hmm... esto es extraño, pero, al parecer otra persona ya se ha logueado con esa cuenta. Te pido que me des unos minutos en lo que verifico esta situación..
        /// </summary>
        internal static string AlreadyLoggedInWithThatAccountMessage {
            get {
                return ResourceManager.GetString("AlreadyLoggedInWithThatAccountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚠️ Te recomiendo que cambies tu contraseña tan pronto te sea posible..
        /// </summary>
        internal static string ChangeYourPasswordWarningMessage {
            get {
                return ResourceManager.GetString("ChangeYourPasswordWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disculpa... tu intento de inicio de sesión no ha sido aprobado..
        /// </summary>
        internal static string DeniedLoginAttemptMessage {
            get {
                return ResourceManager.GetString("DeniedLoginAttemptMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        internal static string DescriptionField {
            get {
                return ResourceManager.GetString("DescriptionField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Pero... yo ni si quiera te conozco. ಠ_ಠ&quot;.
        /// </summary>
        internal static string DontKnowYouMessage {
            get {
                return ResourceManager.GetString("DontKnowYouMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista de paquetes vacía 📭.
        /// </summary>
        internal static string EmptyPackageListMessage {
            get {
                return ResourceManager.GetString("EmptyPackageListMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu contraseña no puede ser un mensaje en blanco. 😑.
        /// </summary>
        internal static string EmptyPasswordMessage {
            get {
                return ResourceManager.GetString("EmptyPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}\nListo, respuesta: *{1}*.
        /// </summary>
        internal static string InlineQueryAnswerMessage {
            get {
                return ResourceManager.GetString("InlineQueryAnswerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to permitir.
        /// </summary>
        internal static string LoginAttemptAllowKeyword {
            get {
                return ResourceManager.GetString("LoginAttemptAllowKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permitir.
        /// </summary>
        internal static string LoginAttemptAllowText {
            get {
                return ResourceManager.GetString("LoginAttemptAllowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to denegar.
        /// </summary>
        internal static string LoginAttemptDenyKeyword {
            get {
                return ResourceManager.GetString("LoginAttemptDenyKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denegar.
        /// </summary>
        internal static string LoginAttemptDenyText {
            get {
                return ResourceManager.GetString("LoginAttemptDenyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey {0}, el usuario {1} está tratando de iniciar sesión con tu cuenta de Flypack, ¿estás de acuerdo con esto?.
        /// </summary>
        internal static string LoginAttemptRequestPermissionMessage {
            get {
                return ResourceManager.GetString("LoginAttemptRequestPermissionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Hola {0}! He podido iniciar sesión con tu usuario, ahora me mantendré monitoreando el estado de tus paquetes..
        /// </summary>
        internal static string LoginWelcomeMessage {
            get {
                return ResourceManager.GetString("LoginWelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.
        /// </summary>
        internal static string NoKeyword {
            get {
                return ResourceManager.GetString("NoKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string NoText {
            get {
                return ResourceManager.GetString("NoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tienes {0} paquetes en proceso.
        /// </summary>
        internal static string PackagesInProcessMessage {
            get {
                return ResourceManager.GetString("PackagesInProcessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado de paquetes.
        /// </summary>
        internal static string PackageStatus {
            get {
                return ResourceManager.GetString("PackageStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to libras.
        /// </summary>
        internal static string PoundsText {
            get {
                return ResourceManager.GetString("PoundsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recibido.
        /// </summary>
        internal static string ReceivedByField {
            get {
                return ResourceManager.GetString("ReceivedByField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, mándame tu usuario y contraseña; así podré revisar tus paquetes y sus estados. No te preocupes, mantendre tus credenciales bien seguras.\n\nMándalos de esta forma: _usuario, contraseña_ .
        /// </summary>
        internal static string SendUsernameAndPasswordMessage {
            get {
                return ResourceManager.GetString("SendUsernameAndPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, mándame tu usuario y contraseña.\n\nMándalos de esta forma: *usuario, contraseña*, utilizando una coma (,) en medio de..
        /// </summary>
        internal static string SendUsernameAndPasswordSecondMessage {
            get {
                return ResourceManager.GetString("SendUsernameAndPasswordSecondMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        internal static string StatusField {
            get {
                return ResourceManager.GetString("StatusField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Estás seguro que quieres detener el bot?.
        /// </summary>
        internal static string StopBotConfirmationMessage {
            get {
                return ResourceManager.GetString("StopBotConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A partir de este momento ya no recibirás más notificaciones sobre los paquetes asociados a la cuenta FLY-{0}. El usuario que se ha logueado previamente ha detenido las funciones del bot.\nSi deseas, puedes iniciar sesión usando el comando /start..
        /// </summary>
        internal static string StoppedBotAuthorizedUsersMessage {
            get {
                return ResourceManager.GetString("StoppedBotAuthorizedUsersMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Así mismo, los usuarios que has autorizado previamente han sido removidos y dejarán de recibir notificaciones..
        /// </summary>
        internal static string StoppedBotFollowUpMessage {
            get {
                return ResourceManager.GetString("StoppedBotFollowUpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A partir de este momento ya no recibirás más notificaciones sobre tus paquetes. De igual forma, la información relacionada a tu usuario ha sido eliminada..
        /// </summary>
        internal static string StoppedBotMessage {
            get {
                return ResourceManager.GetString("StoppedBotMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking.
        /// </summary>
        internal static string TrackingField {
            get {
                return ResourceManager.GetString("TrackingField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña ha sido actualizada. 🎉.
        /// </summary>
        internal static string UpdatedPasswordMessage {
            get {
                return ResourceManager.GetString("UpdatedPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usuario, contraseña.
        /// </summary>
        internal static string UsernameAndPasswordPlaceholder {
            get {
                return ResourceManager.GetString("UsernameAndPasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Me parece que ya hemos pasado por esto, quizás ya has enviado ese comando anteriormente. _Déjà vu_.
        /// </summary>
        internal static string WeHaveAlreadyMetMessage {
            get {
                return ResourceManager.GetString("WeHaveAlreadyMetMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peso.
        /// </summary>
        internal static string WeightField {
            get {
                return ResourceManager.GetString("WeightField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Hola! Como tal vez ya sepas, este bot te ayudará con el seguimiento de tus paquetes de [Flypack](https://www.flypack.com.do).\n_Este bot no posee ninguna relación jurídica con la empresa Flypack o sus allegados._.
        /// </summary>
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña parece ser incorrecta. 🥴&quot;.
        /// </summary>
        internal static string WrongPasswordMessage {
            get {
                return ResourceManager.GetString("WrongPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Usuario y contraseña incorrectos*\nPor favor, mándame tu usuario y contraseña una vez más.\n\nMándalos de esta forma: _usuario, contraseña_.
        /// </summary>
        internal static string WrongUsernameAndPasswordMessage {
            get {
                return ResourceManager.GetString("WrongUsernameAndPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to si.
        /// </summary>
        internal static string YesKeyword {
            get {
                return ResourceManager.GetString("YesKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sí.
        /// </summary>
        internal static string YesText {
            get {
                return ResourceManager.GetString("YesText", resourceCulture);
            }
        }
    }
}
