name: Tags PR Merge Commit

on: 
  pull_request:
    types:
    - closed
    branches:
      - master

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      
      - name: Tag this version
        uses: langroodi/tagize@v1
    
